### ISSUE TITLE
TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by thouveng** [NYTimes/collectd-rabbitmq#10]
I have the following error:
[2015-02-12 17:19:15]   File "/usr/lib/collectd/rabbitmq.py", line 224, in read
    dispatch_queue_metrics(queue_data, vhost)
[2015-02-12 17:19:15]   File "/usr/lib/collectd/rabbitmq.py", line 136, in dispatch_queue_metrics
    values = list(queue.get(name, 0),)
[2015-02-12 17:19:15] TypeError: 'int' object is not iterable

I looked in the code and the first name in QUEUE_STATS is 'memory'. So a queue.get('memory', 0) is effectively returning an int. It seems that it is the commit 0bf1abcf50 that introduces the problem.

**Comment by huaxings** [comment]
[Line 134](https://github.com/NYTimes/collectd-rabbitmq/blob/master/rabbitmq.py#L134) is causing the problem. I have added a comment in the change you mentioned.
Also, there is another bug in [Line 146](https://github.com/NYTimes/collectd-rabbitmq/blob/master/rabbitmq.py#L146). The missing default value for `details.get(detail,)` will cause a float() conversion error.

**Comment by jimbydamonk** [comment]
This should be fix thanks to @huaxings in commit https://github.com/NYTimes/collectd-rabbitmq/commit/c81001855d51c00e7de7d5cce1ad237487a0bfc9
