### ISSUE TITLE
Metric names collision in clusters with graphite output

### ISSUE THREAD

**Issue by ttarczynski** [NYTimes/collectd-rabbitmq#15]
When using this plugin with write_graphite output on multiple rabbitmq nodes I have the exchanges and queues metrics overwritten by each node.

I use the following prefix configuration for write_graphite:

```
    Prefix "${cluster}.collectd."
```

Then other plugins write to graphite paths like:

```
mq.collectd.mq1.memory.memory-free
mq.collectd.mq2.memory.memory-free
```
where:
- `mq` -- cluster name
- `mq1` -- host name
- `memory` -- plugin name

But the collectd-rabbitmq exchanges and queues metrics use the graphite vhost name in place of the host name. Then metrics from multiple nodes (in the same cluster) are written with the same graphite path, e.g.:

```
mq.collectd.rabbitmq_default.queues-test.ack
```
where:
- `default` -- rabbitmq vhost name
- `test` -- rabbitmq queue name

I need a possibility to include hostname in the exchanges and queues metrics names coming from collectd-rabbitmq.

**Comment by jimbydamonk** [comment]
I just merge PR #34 and cut a release https://github.com/NYTimes/collectd-rabbitmq/tree/v1.7.0
