### ISSUE TITLE
collectd python lib version

### ISSUE THREAD

**Issue by jtaleric** [NYTimes/collectd-rabbitmq#24]
What is the version of collectd python lib do you use? The latest from pip complains about the register method.

**Comment by jimbydamonk** [comment]
This does not use anything from pip. It is a collectd python based plugin. 
The collectd python pluging embeds a python interpreter into collectd.

Perhaps there is a conflict somehwere. Can you share the error.

**Comment by jtaleric** [comment]
Yup - I didn't realize that RabbitMQ shipped its own Python w/ this lib... I was trying to run via the interpreter... Got it figured out. Thanks!
