### ISSUE TITLE
Plugin hangs on startup

### ISSUE THREAD

**Issue by adam-bloom** [nytimes/collectd-rabbitmq#55]
Using the latest version, I frequently find that the plugin simply hangs. My collectd config:

```<Plugin python>
  LogTraces true
  Interactive false
  Import "collectd_rabbitmq.collectd_plugin"
  <Module "collectd_rabbitmq.collectd_plugin">

    Username "guest"
    Password "guest"
    Realm "RabbitMQ Management"
    Host "localhost"
    Port "15672"

  </Module>
</Plugin>
```

And the resulting log:
```
[2017-03-31 16:40:50] plugin_load: plugin "python" successfully loaded.
[2017-03-31 16:40:51] plugin_load: plugin "write_log" successfully loaded.
[2017-03-31 16:40:52] Initialization complete, entering read-loop.
```

When I compiled collectd with debug enabled, it would log one additional line before hanging:

`[2017-03-30 20:22:03] Getting info for http://localhost:15672/api/nodes`

A curl to that route returns successfully (and very quickly!), yet the collectd plugin simply hangs.
Any ideas? I can get it to error (say, put the wrong username in the config), but can't get it to repeatedly behave properly. It has worked a handful of times, but I can't consistently reproduce that.

**Comment by jimbydamonk** [comment]
That is strange. collectd is pretty good about not letting plugins hang. 
I will see if I can recreate the plugin hanging.

**Comment by jimbydamonk** [comment]
I have tried a number of times to reproduce.. and I can't.
What OS, rabbitmq, and collectd version are you running ?
